const express = require('express');
const router  = express.Router();
const { requireAuth } = require('../middleware/auth');
const { requireRole }  = require('../middleware/role');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const fs   = require('fs');
const path = require('path');

const UPLOADS_DIR = path.join(__dirname, '../../uploads');

// GET /api/documents/:id/view — smart document viewer
router.get('/:id/view', requireAuth, async (req, res) => {
  try {
    const doc = await prisma.document.findUnique({
      where: { id: Number(req.params.id) },
      include: { author: { select: { fullName: true } } },
    });
    if (!doc) return res.status(404).send('<p>Document not found</p>');

    const fp = doc.filePath;

    // ── JSON requirements file ──
    if (fp && (fp.endsWith('.json') || fp.startsWith('req-'))) {
      const fullPath = path.join(UPLOADS_DIR, path.basename(fp));
      let reqs = [];
      let title = doc.name.replace('.requirements.json', '');
      try {
        const raw = fs.readFileSync(fullPath, 'utf-8');
        const parsed = JSON.parse(raw);
        reqs  = parsed.requirements || [];
        title = parsed.title || title;
      } catch (e) {
        return res.status(500).send('<p>Could not read requirements file.</p>');
      }

      const rows = reqs.map(r => `
        <tr>
          <td>${escV(r.id)}</td>
          <td>${escV(r.type)}</td>
          <td>${escV(r.priority || 'Med')}</td>
          <td>${escV(r.actor || 'System')}</td>
          <td>${escV(r.requirement)}</td>
          <td>${escV(r.acceptance || '—')}</td>
        </tr>`).join('');

      const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${escV(title)} — AI Audit Gate</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet"/>
<style>
*{box-sizing:border-box;margin:0;padding:0;}
body{font-family:'Inter',sans-serif;background:#f8f9fb;color:#1a1a2e;padding:32px;}
.header{display:flex;align-items:center;gap:14px;margin-bottom:28px;}
.logo{width:36px;height:36px;}
.brand{font-size:22px;font-weight:800;color:#1a1a2e;letter-spacing:-0.02em;}
.brand span{color:#E53935;}
h1{font-size:20px;font-weight:700;color:#1a1a2e;margin-bottom:6px;}
.meta{font-size:12px;color:#666;margin-bottom:24px;}
table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);}
th{background:#E53935;color:#fff;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;padding:10px 12px;text-align:left;}
td{padding:10px 12px;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;line-height:1.5;}
tr:last-child td{border-bottom:none;}
tr:hover td{background:#fef9f9;}
.badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:700;}
.req-id{font-family:monospace;font-size:11px;background:#f0f0f0;padding:2px 6px;border-radius:4px;}
.actions{margin-top:20px;display:flex;gap:10px;}
button{padding:9px 20px;border:none;border-radius:6px;font-size:13px;font-weight:600;cursor:pointer;}
.btn-primary{background:#E53935;color:#fff;}
.btn-secondary{background:#f0f0f0;color:#333;}
@media print{.actions{display:none;} body{padding:16px;} table{box-shadow:none;}}
</style>
</head>
<body>
<div class="header">
  <svg class="logo" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M50 5L61.2257 39.5491H97.5528L68.1636 60.9017L79.3893 95.4509L50 74.0983L20.6107 95.4509L31.8364 60.9017L2.44717 39.5491H38.7743L50 5Z" fill="#E53935"/>
  </svg>
  <span class="brand">nab <span>| AI Audit Gate</span></span>
</div>
<h1>${escV(title)}</h1>
<p class="meta">Author: ${escV(doc.author?.fullName || 'Unknown')} &nbsp;·&nbsp; Version: ${escV(doc.version || 'v1.0')} &nbsp;·&nbsp; Requirements: ${reqs.length} &nbsp;·&nbsp; Generated by AI (ISO 29148)</p>
<table>
  <thead><tr><th>ID</th><th>Type</th><th>Priority</th><th>Actor</th><th>Requirement</th><th>Acceptance Criteria</th></tr></thead>
  <tbody>${rows}</tbody>
</table>
<div class="actions">
  <button class="btn-primary" onclick="window.print()">🖨️ Print / Save as PDF</button>
  <button class="btn-secondary" onclick="window.history.back()">← Back</button>
</div>
</body>
</html>`;
      return res.send(html);
    }

    // ── Demo / null filePath ──
    if (!fp) {
      const docName = doc.name || 'SRS Document';
      const fakeTitle = docName.replace(/\..*$/, '').replace(/[_-]/g, ' ');
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${escV(fakeTitle)} — Demo SRS</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet"/>
<style>
*{box-sizing:border-box;margin:0;padding:0;}
body{font-family:'Inter',sans-serif;background:#f8f9fb;color:#1a1a2e;padding:32px;max-width:900px;margin:0 auto;}
.header{display:flex;align-items:center;gap:14px;margin-bottom:28px;}
.brand{font-size:22px;font-weight:800;color:#1a1a2e;letter-spacing:-0.02em;}
.brand span{color:#E53935;}
.demo-badge{display:inline-block;background:#E53935;color:#fff;font-size:11px;font-weight:700;padding:3px 10px;border-radius:10px;letter-spacing:.05em;margin-bottom:16px;}
h1{font-size:22px;font-weight:800;color:#1a1a2e;margin-bottom:8px;}
h2{font-size:15px;font-weight:700;color:#1a1a2e;margin:24px 0 10px;}
p{font-size:13px;line-height:1.7;color:#444;margin-bottom:12px;}
table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);margin-top:12px;}
th{background:#E53935;color:#fff;font-size:11px;font-weight:700;text-transform:uppercase;padding:10px 12px;text-align:left;}
td{padding:10px 12px;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;line-height:1.5;}
tr:last-child td{border-bottom:none;}
.req-id{font-family:monospace;font-size:11px;background:#f0f0f0;padding:2px 6px;border-radius:4px;}
.actions{margin-top:24px;display:flex;gap:10px;}
button{padding:9px 20px;border:none;border-radius:6px;font-size:13px;font-weight:600;cursor:pointer;}
.btn-primary{background:#E53935;color:#fff;}
.btn-secondary{background:#f0f0f0;color:#333;}
@media print{.actions{display:none;}}
</style>
</head>
<body>
<div class="header">
  <svg width="36" height="36" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M50 5L61.2257 39.5491H97.5528L68.1636 60.9017L79.3893 95.4509L50 74.0983L20.6107 95.4509L31.8364 60.9017L2.44717 39.5491H38.7743L50 5Z" fill="#E53935"/>
  </svg>
  <span class="brand">nab <span>| AI Audit Gate</span></span>
</div>
<div class="demo-badge">DEMO DOCUMENT</div>
<h1>${escV(fakeTitle)}</h1>
<p><strong>Document ID:</strong> ${doc.id} &nbsp;·&nbsp; <strong>Version:</strong> ${escV(doc.version || 'v1.0')} &nbsp;·&nbsp; <strong>Status:</strong> ${escV(doc.status || 'draft')}</p>

<h2>1. Introduction</h2>
<p>This Software Requirements Specification (SRS) defines the functional and non-functional requirements for the ${escV(fakeTitle)} system. This document is intended for use by the business analysis team, development engineers, and quality assurance stakeholders at NAB Vietnam. All requirements are written in accordance with ISO/IEC/IEEE 29148:2018 standards.</p>

<h2>2. Scope</h2>
<p>The system shall provide end-to-end capabilities for managing ${escV(fakeTitle.toLowerCase())} operations. The platform integrates with NAB's existing core banking infrastructure and must comply with local financial regulations (SBV Circular 09/2020/TT-NHNN) and international data protection standards.</p>

<h2>3. Functional Requirements</h2>
<table>
  <thead><tr><th>ID</th><th>Type</th><th>Priority</th><th>Actor</th><th>Requirement</th><th>Acceptance Criteria</th></tr></thead>
  <tbody>
    <tr><td><span class="req-id">REQ-F001</span></td><td>Functional</td><td>High</td><td>User</td><td>The system <strong>shall</strong> authenticate users using a registered credential and issue a session token valid for 30 minutes.</td><td>Valid credentials → session token issued within 2s</td></tr>
    <tr><td><span class="req-id">REQ-F002</span></td><td>Functional</td><td>High</td><td>System</td><td>The system <strong>shall</strong> invalidate the session token after 30 minutes of inactivity and require re-authentication.</td><td>Token rejected after 30 min idle; user redirected to login</td></tr>
    <tr><td><span class="req-id">REQ-F003</span></td><td>Functional</td><td>High</td><td>System</td><td>The system <strong>shall</strong> lock an account for 1,800 seconds after 5 consecutive failed authentication attempts.</td><td>Account locked; lockout timer displayed; unlocks after 30 min</td></tr>
    <tr><td><span class="req-id">REQ-NF001</span></td><td>Non-Functional</td><td>High</td><td>System</td><td>The system <strong>shall</strong> process all API requests within 500 ms under a load of 500 concurrent users at ≥ 95th percentile.</td><td>Load test passes at 500 RPS with p95 latency ≤ 500 ms</td></tr>
    <tr><td><span class="req-id">REQ-NF002</span></td><td>Non-Functional</td><td>Medium</td><td>System</td><td>The system <strong>shall</strong> achieve 99.9% uptime measured on a rolling 30-day window, excluding scheduled maintenance windows.</td><td>Monthly uptime report ≥ 99.9%; alerting in place for downtime</td></tr>
    <tr><td><span class="req-id">REQ-SEC001</span></td><td>Security</td><td>High</td><td>System</td><td>The system <strong>shall</strong> encrypt all data in transit using TLS 1.2 or higher and all data at rest using AES-256.</td><td>Security scan shows no plaintext transmission; encryption verified in storage audit</td></tr>
  </tbody>
</table>

<div class="actions">
  <button class="btn-primary" onclick="window.print()">🖨️ Print / Save as PDF</button>
  <button class="btn-secondary" onclick="window.history.back()">← Back</button>
</div>
</body>
</html>`;
      return res.send(html);
    }

    // ── Regular file: redirect to static uploads ──
    return res.redirect(`/uploads/${path.basename(fp)}`);

  } catch (err) {
    res.status(500).send('<p>Error: ' + escV(err.message) + '</p>');
  }
});

function escV(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// GET /api/documents/:id
router.get('/:id', requireAuth, async (req, res) => {
  try {
    const doc = await prisma.document.findUnique({
      where: { id: Number(req.params.id) },
      include: { author: { select: { fullName: true } }, auditResult: true, approval: true },
    });
    if (!doc) return res.status(404).json({ error: 'Document not found' });
    res.json({ document: doc });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/documents/:id/audit — BA triggers mock audit
router.post('/:id/audit', requireAuth, requireRole('BA'), async (req, res) => {
  try {
    const doc = await prisma.document.findUnique({ where: { id: Number(req.params.id) } });
    if (!doc) return res.status(404).json({ error: 'Document not found' });

    // ── Mock AI audit scoring (sẽ thay bằng real AI call sau) ──
    const score = Math.floor(Math.random() * 40) + 55; // 55-95
    const issuesCount = Math.floor((100 - score) * 0.8);
    const mockIssues = [
      { type: 'Ambiguous language', severity: 'medium', count: Math.floor(issuesCount * 0.4) },
      { type: 'Missing fields',     severity: 'low',    count: Math.floor(issuesCount * 0.3) },
      { type: 'Logic conflict',     severity: 'high',   count: Math.floor(issuesCount * 0.3) },
    ];

    // Upsert audit result
    const auditResult = await prisma.auditResult.upsert({
      where:  { documentId: doc.id },
      create: { documentId: doc.id, score, totalReqs: doc.reqCount || 50, issuesCount, issuesJson: JSON.stringify(mockIssues) },
      update: { score, issuesCount, issuesJson: JSON.stringify(mockIssues), auditedAt: new Date() },
    });

    // Cập nhật document
    await prisma.document.update({
      where: { id: doc.id },
      data:  { healthScore: score, status: score >= 75 ? 'auditing' : 'revision' },
    });

    res.json({ auditResult, score });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/documents/:id/submit — BA nộp lên Senior BA
router.post('/:id/submit', requireAuth, requireRole('BA'), async (req, res) => {
  try {
    const doc = await prisma.document.findUnique({ where: { id: Number(req.params.id) } });
    if (!doc) return res.status(404).json({ error: 'Document not found' });
    if (!doc.healthScore) return res.status(400).json({ error: 'Document must be audited before submitting' });

    const approval = await prisma.approval.upsert({
      where:  { documentId: doc.id },
      create: { documentId: doc.id, submittedById: req.user.id },
      update: { status: 'pending', submittedById: req.user.id, submittedAt: new Date() },
    });
    await prisma.document.update({ where: { id: doc.id }, data: { status: 'auditing' } });

    res.json({ approval });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
